"""empty message

Revision ID: 63ed13b95683
Revises: 2bb05e561bd9
Create Date: 2019-06-30 18:02:59.090642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63ed13b95683'
down_revision = '2bb05e561bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classfy', sa.Column('class_name1', sa.String(length=100), nullable=True))
    op.drop_index('class_name', table_name='classfy')
    op.create_unique_constraint(None, 'classfy', ['class_name1'])
    op.drop_column('classfy', 'class_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classfy', sa.Column('class_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'classfy', type_='unique')
    op.create_index('class_name', 'classfy', ['class_name'], unique=True)
    op.drop_column('classfy', 'class_name1')
    # ### end Alembic commands ###
