"""empty message

Revision ID: c3c3b658f40e
Revises: 9927d546faf7
Create Date: 2019-06-27 17:27:52.566107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c3b658f40e'
down_revision = '9927d546faf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artical', sa.Column('artical_tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artical', 'artical_tag')
    # ### end Alembic commands ###
