"""empty message

Revision ID: ea061e8f7bc0
Revises: 978aa6e5a404
Create Date: 2019-06-30 23:40:53.365843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea061e8f7bc0'
down_revision = '978aa6e5a404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'login_time')
    # ### end Alembic commands ###
